language: python
python:
    #- 2.6
    #- 2.7
    - pypy

env:
  - TWISTED_VERSION=12.2.0
  #- TWISTED_VERSION=12.1.0

install:
  - pip install Twisted==$TWISTED_VERSION
  - pip install -r requirements-dev.txt --use-mirrors

script:
  - pep8 treq
  - pyflakes treq
  - strace trial treq
